os:
  - linux

env:
  - WINEARCH=win32
  - WINEARCH=""

cache: apt

before_install:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 800x600x16"

before_script:
  - sudo add-apt-repository -y ppa:pipelight/stable
  - sudo apt-get update -qq
  - sudo apt-get install -y --install-recommends wine-staging wine-staging-compat subversion
  - wget https://dl.dropboxusercontent.com/u/38458267/msys2/msys2-base-i686-20150512-20150805.deb
  - sudo dpkg -i msys2-base-i686-20150512-20150805.deb
  - msys2init

language: c

compiler:
  - gcc

script:
  - srcdir=~/src
  - _realname=virt-viewer
  - pkgbuild_repo=https://github.com/Alexpux/MINGW-packages/trunk/mingw-w64-virt-viewer-git
  - svn co ${pkgbuild_repo} ${srcdir}
  - ln -svf ${PWD} ${srcdir}/${_realname}
  - cp ${srcdir}/PKGBUILD ~
  - msys2run "makepkg-mingw -s --noconfirm --noprogressbar --noextract --skippgpcheck -f"